development:
  adapter: mysql2
  database: vcard_dev
  timeout: 5000
  user: root

test:
  adapter: mysql2
  database: vcard_test
  timeout: 5000
  user: root

production:
  adapter: mysql2
  database: vcard_prod
  timeout: 5000
  user: root
